version: "3.8"

networks:
  codluck-backend:

services:
  postgres:
    container_name: postgres-codluck
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - codluck-backend

  pgadmin:
    container_name: pgadmin-codluck
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - codluck-backend

  redis:
    image: redis:6.0.7
    container_name: redis-codluck
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - codluck-backend

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight-codluck
    ports:
      - 8002:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - codluck-backend

  # nginx:
  #   image: nginx:latest
  #   container_name: reverse_proxy
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - capstone
  #   networks:
  #     - capstone-backend

volumes:
  pgdata:
  redis_volume_data:
  redis_insight_volume_data:
