version: "3.8"

networks:
  codluck-backend:

services:
  postgres:
    container_name: postgres-codluck
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - codluck-backend

  pgadmin:
    container_name: pgadmin-codluck
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - codluck-backend

  redis:
    image: redis:6.0.7
    container_name: redis-codluck
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - codluck-backend

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight-codluck
    ports:
      - 5540:5540
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - codluck-backend

  backend-b2b:
    image: dihson103/backend-b2b
    container_name: backend-b2b
    build:
      context: .
      dockerfile: Web-backend/src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgres-codluck:5432;User Id=postgres;Password=postgres;Database=CodLuckProject
      - ConnectionStrings__Redis=redis-codluck:6379
      - jwtOption__Issuer=http://backend-b2b:7001
      - jwtOption__Audience=http://backend-b2b:7001
      - jwtOption__SecretKey=BSMiu0y9GwkHjCTy8J3gqfivqzdzNQp6
      - jwtOption__ExpireMin=30
    ports:
      - 7001:8080
    depends_on:
      - postgres
      - redis
    networks:
      - codluck-backend

  nginx:
    image: nginx:latest
    container_name: reverse_proxy_codluck
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend-b2b
    networks:
      - codluck-backend

volumes:
  pgdata:
  redis_volume_data:
  redis_insight_volume_data:
