import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Trang đăng ký',
  description: 'Generated by create next app'
}

export default async function RegisterLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <>{children}</>
}
