import { Card } from '@/components/ui/card'
import { Tabs, TabsContent } from '@/components/ui/tabs'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Thêm sự kiện',
  description: 'Generated by create next app'
}

export default async function EventLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // <Tabs defaultValue='all'>
    //   <TabsContent value='all'>
    //     <Card x-chunk='dashboard-06-chunk-0'>{children}</Card>
    //   </TabsContent>
    // </Tabs>
    <>{children}</>
  )
}
